export const EVENTS = [
  {
    id: 24323,
    venue: 'Miami Beach',
    location: 'Miami, Florida, USA',
    date: 'November 8, 2019',
    time: '7:30 PM',
  },
  {
    id: 24323,
    venue: 'Friends Arena',
    location: 'Råsta Strandväg 1, 169 56 Solna, Sweden',
    date: 'Thursday, December 5, 2019',
    time: '7:30 PM',
  },
  {
    id: 23210,
    venue: 'Paradiso',
    location: 'Weteringschans 6-8, Amsterdam, Netherlands',
    date: 'Thursday, September 26, 2019,',
    time: '7:30 PM',
  },
  {
    id: 23210,
    venue: 'NOTO Philadelphia',
    location: '1209 Vine Street, Philadelphia, PA',
    date: 'Saturday, September 28, 2019,',
    time: '10:30 PM',
  },
  {
    id: 24210,
    venue: 'Culture and Congress Center Jahrhunderthalle GmbH',
    location: 'Pfaffenwiese 301, Frankfurt am Main, Germany',
    date: 'Saturday, September 28, 2019',
    time: '7:30 PM',
  },
  {
    id: 24210,
    venue: 'Ziggo Dome',
    location: 'De Passage 100, Amsterdam, Netherlands',
    date: 'Tuesday, October 1, 2019,',
    time: '8:00 PM',
  },
  {
    id: 24210,
    venue: `L'Olympia Bruno Coquatrix`,
    location: '28 Boulevard des Capucines, Paris, France',
    date: 'Friday, October 4, 2019,',
    time: '8:00 PM',
  },
];
